sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - echo $TEST_DELETE_ME "${TEST_DELETE_ME}"
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
# custom travis_after_all script under @remy's private gist
  - 'curl -Lo travis_after_all.py https://git.io/vzaBe'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
